# Generated by Django 3.2.dev20201119200004 on 2020-11-20 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DCommentmeta',
            fields=[
                ('meta_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_id', models.IntegerField(db_index=True, default=0)),
                ('meta_key', models.CharField(db_index=True, default='', max_length=255)),
                ('meta_value', models.TextField()),
            ],
            options={
                'db_table': 'd_commentmeta',
            },
        ),
        migrations.CreateModel(
            name='DComments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_post_id', models.IntegerField(db_index=True, default=0)),
                ('comment_author', models.TextField()),
                ('comment_author_email', models.CharField(default='', max_length=100)),
                ('comment_author_url', models.CharField(default='', max_length=200)),
                ('comment_author_ip', models.CharField(default='', max_length=100)),
                ('comment_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('comment_date_gmt', models.DateTimeField(blank=True, null=True)),
                ('comment_content', models.TextField()),
                ('comment_karma', models.IntegerField(default=0)),
                ('comment_approved', models.CharField(db_index=True, default='1', max_length=20)),
                ('comment_agent', models.CharField(default='', max_length=255)),
                ('comment_type', models.CharField(default='comment', max_length=20)),
                ('comment_parent', models.IntegerField(db_index=True, default=0)),
                ('user_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'd_comments',
            },
        ),
        migrations.CreateModel(
            name='DOptions',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('option_name', models.CharField(db_index=True, default='', max_length=191)),
                ('option_value', models.TextField()),
                ('autoload', models.CharField(default='yes', max_length=20)),
            ],
            options={
                'db_table': 'd_options',
            },
        ),
        migrations.CreateModel(
            name='DPostmeta',
            fields=[
                ('meta_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.IntegerField(db_index=True, default=0)),
                ('meta_key', models.CharField(db_index=True, default='', max_length=255)),
                ('meta_value', models.TextField()),
            ],
            options={
                'db_table': 'd_postmeta',
            },
        ),
        migrations.CreateModel(
            name='DPosts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_author', models.IntegerField(db_index=True)),
                ('post_date', models.DateTimeField(blank=True, null=True)),
                ('post_date_gmt', models.DateTimeField(blank=True, null=True)),
                ('post_content', models.TextField()),
                ('post_title', models.CharField(max_length=255)),
                ('post_excerpt', models.TextField(default='')),
                ('post_status', models.CharField(default='publish', max_length=20)),
                ('comment_status', models.CharField(default='open', max_length=20)),
                ('ping_status', models.CharField(default='open', max_length=20)),
                ('post_password', models.CharField(default='', max_length=255)),
                ('post_name', models.CharField(db_index=True, default='', max_length=200)),
                ('to_ping', models.TextField()),
                ('pinged', models.TextField()),
                ('post_modified', models.DateTimeField(blank=True, null=True)),
                ('post_modified_gmt', models.DateTimeField(blank=True, null=True)),
                ('post_content_filtered', models.TextField()),
                ('post_parent', models.IntegerField(db_index=True, default=0)),
                ('guid', models.CharField(default='', max_length=255)),
                ('menu_order', models.IntegerField(default=0)),
                ('post_type', models.CharField(default='post', max_length=20)),
                ('post_mime_type', models.CharField(default='', max_length=100)),
                ('comment_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'd_posts',
            },
        ),
        migrations.CreateModel(
            name='DUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_login', models.CharField(db_index=True, default='', max_length=60)),
                ('user_pass', models.CharField(default='', max_length=255)),
                ('user_nicename', models.CharField(db_index=True, default='', max_length=50)),
                ('user_email', models.CharField(db_index=True, default='', max_length=100)),
                ('user_url', models.CharField(default='', max_length=100)),
                ('user_registered', models.DateTimeField(blank=True, null=True)),
                ('user_activation_key', models.CharField(default='', max_length=255)),
                ('user_status', models.IntegerField(default=0)),
                ('display_name', models.CharField(default='', max_length=250)),
            ],
            options={
                'db_table': 'd_users',
            },
        ),
        migrations.CreateModel(
            name='DUsermeta',
            fields=[
                ('umeta_id', models.AutoField(primary_key=True, serialize=False)),
                ('meta_key', models.CharField(db_index=True, default='', max_length=255)),
                ('meta_value', models.TextField()),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='demo.dusers')),
            ],
            options={
                'db_table': 'd_usermeta',
            },
        ),
    ]
